### PR TITLE
Work around TreeSitter incompatibility with Electron 22

### LINKED ISSUE #164: Cucumber.io doesn't work properly on VS Code v1.78.2
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 
image

- OS Version: 
image

Steps to Reproduce:

1. Update VS code to 1.78.2
2. My Cucumber extension doesn't work properly when I update VS Code to v1.78.2
3. Show an error message like this
image

[Error - 12:47:10 PM] Server initialization failed.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_php_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603 
[Error - 12:47:10 PM] Cucumber Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_php_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603 

4. And my .feature file is like this (the color is black and white), I can't  jump to step files, when I click cmd+click on the step feature
image

### PR DESCRIPTION
**Pull request by xeger**
### 🤔 What's changed?

Tweaked the `web-tree-sitter` WASM loader for synchronous operation.

To test these changes, install the [pre-release VSIX file](https://github.com/xeger/cucumber-vscode/releases/tag/v1.8.0) and then edit some Gherkin code.

### ⚡️ What's your motivation? 

Fixes #164 

VS Code 1.78 ships with Electron 22, and something has changed in V8 to make it hostile toward loading the tree-sitter language support WASM. It was recommended to `loadAsync: false` as a workaround, and lo, things seem to work if we monkey patch that workaround into the codebase.

There is no visible impact on performance.

### 🏷️ What kind of change is this?

- 🙃 Crazy hack that helps tide us over until Tree Sitter can make a proper fix.
- See tree-sitter/tree-sitter#2338 for details and tracking.

### ♻️ Anything particular you want feedback on?

This would seem like the only expedient way to restore the plugin's functionality. I've recruited some beta testers from Slack who will hopefully play with it before we publish it. Seems better than nothing, to me!

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

### CODE REVIEW

**Comment by xeger** [comment]
After chatting with mpkorstanje, my plan of action for this PR is never to merge the branch. We'll release a version of the extension from this feature branch.

**Comment by LukasLewandowski** [comment]
Any update? :)

**Comment by xeger** [comment]
Sorry, no; I was waiting until Tree Sitter released their new major version, but I've since confirmed that it's still broken.

See tree-sitter/tree-sitter#2338 for details.

I will see about rebasing this branch off of a recent `main` (to pick up additional fixes) and then releasing.

**Comment by xeger** [comment]
FYI @LukasLewandowski and others -- I've built [a new pre-release VSIX](https://github.com/xeger/cucumber-vscode/releases/tag/v1.8.0) that you can install; it uses a less scary hack to work around the still-unresolved TreeSitter bug, and it upgrades several packages to improve the Gherkin editing experience. I will propose to the rest of the team that we release it as an official 1.8.0.

In the meantime, feel free to use the VSIX linked above and let me know if you have any problems. Thanks!

**Comment by NutriMarc** [comment]
I am still not getting cucumber language features on my feature files. I created these settings in my settings.json to try to fix it but to no avail. Can you help me get important cucumber features like clicking to step definition from feature files? 

`    "files.associations": {
        "*.feature": "feature"
    },
    "cucumber.features": [
        "oneOfManySubprojects/features/**/*.feature"
    ],
    "cucumber.glue": [
        "oneOfManySubprojects/tests-onehub/step-definitions/**/*.js"
    ]
`

**Comment by xeger** [comment]
Closed this PR in favor of waiting for VS Code 1.82.0 which fixes the underlying incompatibility! 🎉

**Pull request closed without merging**
